### ISSUE TITLE
Various missing acronyms

### ISSUE THREAD

**Issue by hugobuddel** [jzoubian/euclidator#4]
Some acronyms that are used in various documents and are missing from the Euclidator:
* IPC: Inter-Pixel Capacitance
* IVV: Integration, Verification & Validation (obsolete, but probably still used)
* SPR: Software Problem Report
* VP: Validation Plan (VPD is there, but is that ever used?)
* MEF: Multi-Extension FITS
* LE1: LEvel 1
* LE3: LEvel 3

**Comment by jzoubian** [comment]
Thanks for feedback.

I will work on an update when I'll get some free time... maybe before the annual meeting.
Up to now, the acronym list is only based on the official doc, and it can probably not be updated enough often.

I was thinking about that, we could add a page to proposed some acronyms (with some kind of validation process, at least to check there is no duplicate and the acronym makes some sens), and print with a different color the "official acronym" and "community acronym".

Anyway I'll keep you in touch.

**Comment by hugobuddel** [comment]
I sent the same acronyms as listed in #2, #3 and here to Christophe, but didn't get a reply. Note that for the acronyms in the other issues I don't actually know the meaning (hence me trying to look them up in the Euclidator).

In that mail I also suggested to make the list a proper github/gitlab project so we can create issues and merge/pull requests. Merge requests seem to be a perfect existing mechanism to propose new acronyms, and issues can be used for missing acronyms for which the meaning is unknown.

**Comment by jzoubian** [comment]
Use the git issue tracker sounds good to me, I will put a link to come directly here.
Good idea, thanks!

**Comment by ycopin** [comment]
I actually uploaded my euclidator under gitlab: https://gitlab.euclid-sgs.uk/ycopin/euclidator, which is now open to pull request.  Teake Nutma was the 1st one to add changes. @hugobuddel could you make a PR for your own additions?

**Comment by hugobuddel** [comment]
Thanks @ycopin!

Created a merge request with some attributes: https://gitlab.euclid-sgs.uk/ycopin/euclidator/merge_requests/2

So closing this.
